name: Client CI/CD

on:
  push:
    branches: [ main ]
    paths: [ client/** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        working-directory: ./client
        run: npm install --production

      - name: Build with webpack
        working-directory: ./client
        run: npm run build

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: client/dist
          single-commit: true
